package com.tashin.tourism.ai.controller;

import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.tashin.tourism.ai.dto.AiChatRequest;
import com.tashin.tourism.ai.dto.AiChatResponse;
import com.tashin.tourism.ai.dto.ExecuteAgentActionRequest;
import com.tashin.tourism.ai.dto.UserPersonalizationDto;
import com.tashin.tourism.ai.service.AiService;
import com.tashin.tourism.ai.service.UserPersonalizationService;
import com.tashin.tourism.common.api.ApiResponse;
import com.tashin.tourism.favorite.service.FavoriteService;
import com.tashin.tourism.trip.service.TripService;
import com.tashin.tourism.user.entity.User;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@RestController
@RequestMapping("/v1/ai")
@RequiredArgsConstructor
@Slf4j
@Tag(name = "AI Assistant & Travel Agent", description = "Endpoints for AI-powered tourism assistance, dynamic itinerary generation, and multi-action agent execution")
public class AiController {

    private final AiService aiService;
    private final UserPersonalizationService userPersonalizationService;
    private final TripService tripService;
    private final FavoriteService favoriteService;

    /**
     * Ask the RAG-powered Sri Lanka Tourism AI Assistant a question.
     * Automatically enriches request with authenticated user profile, favorites, and trips if logged in.
     *
     * POST /api/v1/ai/chat
     */
    @PostMapping("/chat")
    @Operation(summary = "Chat with AI Assistant", description = "Answers tourist queries using live PostgreSQL context, vector document retrieval, and personalized user profile/trips/favorites")
    public ApiResponse<AiChatResponse> chat(
            @Valid @RequestBody AiChatRequest request,
            @AuthenticationPrincipal User user) {

        User currentUser = resolveUser(user);

        UserPersonalizationDto userContext = null;
        if (currentUser != null) {
            try {
                userContext = userPersonalizationService.buildPersonalizationContext(currentUser);
                log.debug("Attached user personalization context for user: {}", currentUser.getEmail());
            } catch (Exception e) {
                log.warn("Could not build user personalization context: {}", e.getMessage());
            }
        }

        AiChatResponse response = aiService.askAi(request, userContext);
        return ApiResponse.success(response);
    }

    /**
     * Execute an AI Travel Agent action proposal (e.g. 1-click Create Trip or Bookmark Favorite).
     *
     * POST /api/v1/ai/agent/execute-action
     */
    @PostMapping("/agent/execute-action")
    @Operation(summary = "Execute AI Travel Agent Action", description = "Executes an action proposal (e.g., CREATE_TRIP, FAVORITE_ENTITY) generated by the AI agent")
    public ApiResponse<Object> executeAgentAction(
            @Valid @RequestBody ExecuteAgentActionRequest request,
            @AuthenticationPrincipal User user) {

        User currentUser = resolveUser(user);
        if (currentUser == null) {
            throw new IllegalArgumentException("You must be logged in to execute travel agent actions");
        }

        String actionType = request.actionType() != null ? request.actionType().toUpperCase() : "";

        return switch (actionType) {
            case "CREATE_TRIP" -> {
                if (request.tripProposal() == null) {
                    throw new IllegalArgumentException("Missing trip proposal payload");
                }
                var createdTrip = tripService.createTrip(currentUser, request.tripProposal());
                yield ApiResponse.success(createdTrip);
            }
            case "FAVORITE_ENTITY" -> {
                if (request.favoriteProposal() == null) {
                    throw new IllegalArgumentException("Missing favorite proposal payload");
                }
                var favorited = favoriteService.addFavorite(currentUser, request.favoriteProposal());
                yield ApiResponse.success(favorited);
            }
            default -> throw new IllegalArgumentException("Unsupported action type: " + actionType);
        };
    }

    private User resolveUser(User user) {
        if (user != null) return user;
        var auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null && auth.getPrincipal() instanceof User u) {
            return u;
        }
        return null;
    }
}
