export const routes = {
  home: "/",
  destinations: "/destinations",
  destination: (slug: string) => `/destinations/${slug}`,
  attractions: "/attractions",
  attraction: (slug: string) => `/attractions/${slug}`,
  experiences: "/experiences",
  experience: (slug: string) => `/experiences/${slug}`,
  restaurants: "/restaurants",
  accommodations: "/accommodations",
  events: "/events",
  search: "/search",
  map: "/map",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  profile: "/profile",
  favorites: "/favorites",
  trips: "/trips",
  admin: {
    dashboard: "/admin",
    destinations: "/admin/destinations",
    attractions: "/admin/attractions",
    experiences: "/admin/experiences",
    providers: "/admin/providers",
    reviews: "/admin/reviews",
    auditLogs: "/admin/audit-logs",
  },
} as const;
